apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: db-cuzfrog
  name: maria
  labels:
    app: maria
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: maria
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: maria
    spec:
      containers:
        - name: database
          image: maria:jammy
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: MARIA_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MARIA_ROOT_PASSWORD
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: database
              mountPath: /var/lib/mysql
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: maria-pvc

